# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-23 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_vitae', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumvitae',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='curriculumvitae',
            name='end_date',
            field=models.CharField(default='Present', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='curriculumvitae',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='curriculumvitae',
            name='start_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='curriculumvitae',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
