# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-23 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_vitae', '0004_auto_20190523_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='description',
            new_name='abstract',
        ),
    ]
