# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-23 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_vitae', '0005_auto_20190523_2140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurriculumVitae',
            new_name='Project',
        ),
    ]
