# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='book',
            name='pub_year',
            field=models.IntegerField(default=0),
        ),
    ]
