# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-04 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
