# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-04 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('color_summary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=200)),
                ('json', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.CharField(default='someURL', max_length=100)),
            ],
        ),
    ]
