# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170626_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.BigIntegerField(default=0),
        ),
    ]
