# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-08 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('books', '0003_auto_20170627_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sites',
            field=models.ManyToManyField(to='sites.Site'),
        ),
    ]
