# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-23 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_sites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sites',
        ),
    ]
